//! Python RNS 1.4.2 golden-vector lock for the RESOURCE layer, plus the live-verifier emitter.
//!
//! `../vectors/resource_vectors.json` is generated by the REAL Python `RNS.Resource` /
//! `ResourceAdvertisement` classes with fixed entropy (`vectors/gen_resource_vectors.py`) —
//! upstream-only vectors, never re-derived. The lite advertisement, ciphertext parts, part
//! requests and delivery proof must match those bytes exactly, and the lite receiver must
//! reassemble the Python-emitted bytes. `vectors/run.sh` additionally pipes the emitter output
//! through a live Python `RNS.Resource` (accept → reassemble → prove → validate).

use rns_lite_core::link::LinkKeys;
use rns_lite_core::resource::{
    ADV_PACKED_MAX, InboundResource, OutboundResource, PROOF_LEN, PartRequestView, REQUEST_MAX,
    ResourceAdv, ResourceError,
};
use std::fmt::Write as _;

const VECTORS: &str = include_str!("../vectors/resource_vectors.json");

fn from_hex(s: &str) -> Vec<u8> {
    assert!(s.len() % 2 == 0, "odd hex length");
    (0..s.len() / 2)
        .map(|i| u8::from_str_radix(&s[2 * i..2 * i + 2], 16).unwrap())
        .collect()
}

fn to_hex(bytes: &[u8]) -> String {
    bytes.iter().fold(
        String::with_capacity(bytes.len() * 2),
        |mut encoded, byte| {
            write!(&mut encoded, "{byte:02x}").expect("writing to a String cannot fail");
            encoded
        },
    )
}

/// Raw JSON value text following `"key":` (the vectors hold only hex strings, ints and flat
/// arrays/objects of them, so no escape handling is needed).
fn value<'a>(json: &'a str, key: &str) -> &'a str {
    let tag = format!("\"{key}\":");
    let at = json
        .find(&tag)
        .unwrap_or_else(|| panic!("missing key {key}"))
        + tag.len();
    json[at..].trim_start()
}

fn object<'a>(json: &'a str, key: &str) -> &'a str {
    let v = value(json, key);
    assert!(v.starts_with('{'), "{key} is not an object");
    &v[..=v.find('}').unwrap()]
}

fn hex_field(json: &str, key: &str) -> Vec<u8> {
    let v = value(json, key);
    assert!(v.starts_with('"'), "{key} is not a string");
    from_hex(&v[1..v[1..].find('"').unwrap() + 1])
}

fn usize_field(json: &str, key: &str) -> usize {
    let v = value(json, key);
    let end = v.find(|c: char| !c.is_ascii_digit()).unwrap();
    v[..end].parse().unwrap()
}

fn hex_array(json: &str, key: &str) -> Vec<Vec<u8>> {
    let v = value(json, key);
    assert!(v.starts_with('['), "{key} is not an array");
    v[..v.find(']').unwrap()]
        .split('"')
        .filter(|s| !s.is_empty() && s.chars().all(|c| c.is_ascii_hexdigit()))
        .map(from_hex)
        .collect()
}

fn arr<const N: usize>(v: Vec<u8>) -> [u8; N] {
    v.try_into().unwrap()
}

/// Link session keys from the pinned handshake material; the lite HKDF derivation must reproduce
/// the Python-derived session key byte-for-byte.
fn vector_keys() -> LinkKeys {
    let init_x: [u8; 32] = arr(hex_field(VECTORS, "init_x25519_priv"));
    let resp_pub: [u8; 32] = arr(hex_field(VECTORS, "resp_x25519_pub"));
    let link_id: [u8; 16] = arr(hex_field(VECTORS, "link_id"));
    let keys = LinkKeys::derive(&init_x, &resp_pub, &link_id);
    assert_eq!(
        keys.combined().as_slice(),
        hex_field(VECTORS, "session_key").as_slice(),
        "lite link key derivation != Python session key"
    );
    keys
}

struct Transcript {
    adv: Vec<u8>,
    parts: Vec<Vec<u8>>,
    requests: Vec<Vec<u8>>,
    proof: [u8; PROOF_LEN],
}

/// Full lite sender -> lite receiver loop for `payload`, returning every wire artifact.
fn lite_transfer(payload: &[u8], keys: &LinkKeys) -> Transcript {
    let random_hash: [u8; 4] = arr(hex_field(VECTORS, "random_hash"));
    let iv: [u8; 16] = arr(hex_field(VECTORS, "iv"));
    let out = OutboundResource::build(payload, keys, &random_hash, &iv).unwrap();

    let mut adv_buf = [0u8; ADV_PACKED_MAX];
    let n = out.advertisement().pack(&mut adv_buf).unwrap();
    let parts: Vec<Vec<u8>> = (0..out.num_parts())
        .map(|i| out.part(i).unwrap().to_vec())
        .collect();

    let parsed = ResourceAdv::parse(&adv_buf[..n]).unwrap();
    let mut inb = InboundResource::from_advertisement(&parsed).unwrap();
    let mut requests = Vec::new();
    while !inb.is_complete() {
        let mut req = [0u8; REQUEST_MAX];
        let rn = inb.build_part_request(&mut req).unwrap();
        requests.push(req[..rn].to_vec());
        let view = PartRequestView::parse(&req[..rn]).unwrap();
        let (idxs, cnt) = out.requested_parts(&view);
        assert!(cnt > 0, "sender had no parts for the receiver request");
        for &i in &idxs[..cnt] {
            assert!(inb.receive_part(&parts[i]));
        }
    }
    let len = inb.assemble(keys).unwrap();
    assert_eq!(len, payload.len());
    assert_eq!(inb.data().unwrap(), payload);
    let mut proof = [0u8; PROOF_LEN];
    inb.build_proof(&mut proof).unwrap();
    assert!(out.validate_proof(&proof));
    Transcript {
        adv: adv_buf[..n].to_vec(),
        parts,
        requests,
        proof,
    }
}

/// The lite bytes must equal the pinned Python bytes, and the lite receiver must accept the
/// PYTHON-emitted advertisement + parts (not just its own).
fn assert_vector(section: &str, keys: &LinkKeys) {
    let obj = object(VECTORS, section);
    let payload = hex_field(obj, "payload");
    let golden_adv = hex_field(obj, "adv");
    let golden_parts = hex_array(obj, "parts");
    let golden_requests = hex_array(obj, "requests");
    let golden_proof = hex_field(obj, "proof_packet");

    let out = OutboundResource::build(
        &payload,
        keys,
        &arr(hex_field(VECTORS, "random_hash")),
        &arr(hex_field(VECTORS, "iv")),
    )
    .unwrap();
    assert_eq!(out.transfer_size(), usize_field(obj, "transfer_size"));
    assert_eq!(out.num_parts(), usize_field(obj, "num_parts"));
    assert_eq!(usize_field(obj, "data_size"), payload.len());
    assert_eq!(
        out.resource_hash().as_slice(),
        hex_field(obj, "resource_hash").as_slice()
    );
    assert_eq!(
        out.expected_proof().as_slice(),
        hex_field(obj, "expected_proof").as_slice()
    );

    let transcript = lite_transfer(&payload, keys);
    assert_eq!(transcript.adv, golden_adv, "{section}: ADV bytes");
    assert_eq!(transcript.parts, golden_parts, "{section}: part bytes");
    assert_eq!(
        transcript.requests, golden_requests,
        "{section}: request bytes"
    );
    assert_eq!(
        transcript.proof.as_slice(),
        golden_proof.as_slice(),
        "{section}: proof bytes"
    );
    let adv = out.advertisement();
    assert_eq!(
        &adv.hashmap[..adv.hashmap_len],
        hex_field(obj, "hashmap").as_slice()
    );

    // Reassemble the PYTHON bytes end-to-end.
    let parsed = ResourceAdv::parse(&golden_adv).unwrap();
    let mut inb = InboundResource::from_advertisement(&parsed).unwrap();
    for part in &golden_parts {
        assert!(inb.receive_part(part));
    }
    assert_eq!(inb.assemble(keys).unwrap(), payload.len());
    assert_eq!(inb.data().unwrap(), payload.as_slice());
    let mut proof = [0u8; PROOF_LEN];
    inb.build_proof(&mut proof).unwrap();
    assert_eq!(proof.as_slice(), golden_proof.as_slice());
}

#[test]
fn lite_resource_matches_python_rns_vectors() {
    assert!(
        value(VECTORS, "rns_version").starts_with("\"1.4.2\""),
        "vectors were not generated by the pinned Python RNS 1.4.2"
    );
    let keys = vector_keys();
    assert_vector("multi", &keys);
    assert_vector("single", &keys);
}

// A real bz2-compressed advertisement from Python RNS parses, then is refused at accept time
// (fail-closed honest subset: the fleet ships without bz2).
#[test]
fn lite_rejects_python_compressed_adv() {
    let obj = object(VECTORS, "compressed_adv");
    let adv = ResourceAdv::parse(&hex_field(obj, "adv")).unwrap();
    assert!(adv.flags.compressed && adv.flags.encrypted);
    assert_eq!(
        adv.transfer_size as usize,
        usize_field(obj, "transfer_size")
    );
    assert_eq!(
        InboundResource::from_advertisement(&adv).unwrap_err(),
        ResourceError::CompressedUnsupported
    );
}

// Emits the ACTUAL lite-emitted wire bytes for vectors/run.sh, which pipes them through a live
// Python RNS.Resource (accept -> reassemble -> prove) via vectors/verify_rust_resource.py.
#[test]
fn emit_resource_transfer_for_python() {
    let keys = vector_keys();
    let payload = hex_field(object(VECTORS, "multi"), "payload");
    let t = lite_transfer(&payload, &keys);
    let parts: Vec<String> = t.parts.iter().map(|p| to_hex(p)).collect();
    let requests: Vec<String> = t.requests.iter().map(|r| to_hex(r)).collect();
    println!(
        "resource payload={} adv={} parts={} requests={} proof={}",
        to_hex(&payload),
        to_hex(&t.adv),
        parts.join(","),
        requests.join(","),
        to_hex(&t.proof)
    );
}
