#!/usr/bin/env python3
"""Authoritative Reticulum RESOURCE transfer parity-vector generator (rns-lite-core resource layer).

Drives the REAL `RNS.Resource` / `RNS.Resource.ResourceAdvertisement` classes from the installed
Python RNS version pinned in `vectors/RNS_VERSION` (never a re-implementation) with fixed entropy,
over a headless link with fake packet/link attributes and stubbed send/cache effects:

  - link session key  = hkdf(64, ECDH(init_x25519, resp_x25519), salt = link_id) — the same fixed
    key material as the lite/rns-protocol compat tests (0x33/0x55 privs, link_id 0xCD*16);
  - `RNS.Identity.get_random_hash` patched so `random_hash` (and the embedded blob prefix) is the
    fixed vector tag, and the Token IV patched fixed — Python then emits byte-reproducible
    advertisement / parts / proof for a fixed payload.

Every artifact is CROSS-CHECKED by running the full Python receive path (Resource.accept →
receive_part → assemble → prove) on the generated bytes: the real RNS receiver must reassemble the
payload and emit the same proof. Aborts unless the installed RNS version matches `RNS_VERSION`;
the harness never installs or upgrades packages itself.
Output: resource_vectors.json (consumed by the rns-lite-core `resource_vectors` test and
verify_rust_resource.py).
"""

import json
import os
import sys
import tempfile
import time
from pathlib import Path
from types import SimpleNamespace

import RNS
from RNS.Cryptography import Token, X25519PrivateKey, X25519PublicKey, hkdf
from RNS.Resource import Resource, ResourceAdvertisement

TARGET_RNS = (Path(__file__).resolve().with_name("RNS_VERSION")).read_text().strip()

INIT_X = bytes([0x33]) * 32   # initiator ephemeral X25519 private (lite compat fixture)
RESP_X = bytes([0x55]) * 32   # responder ephemeral X25519 private
LINK_ID = bytes([0xCD]) * 16
RANDOM_HASH = bytes([0xAB]) * 4
IV = bytes([0x11]) * 16
MULTI_LEN = 2000              # 5 parts at SDU 464 (lite compat fixture payload)
SINGLE_LEN = 100              # 1 part


def payload(n):
    return bytes(i % 251 for i in range(n))


def session_key():
    shared_i = X25519PrivateKey.from_private_bytes(INIT_X).exchange(
        X25519PublicKey.from_public_bytes(
            X25519PrivateKey.from_private_bytes(RESP_X).public_key().public_bytes()))
    shared_r = X25519PrivateKey.from_private_bytes(RESP_X).exchange(
        X25519PublicKey.from_public_bytes(
            X25519PrivateKey.from_private_bytes(INIT_X).public_key().public_bytes()))
    key_i = hkdf(length=64, derive_from=shared_i, salt=LINK_ID, context=None)
    key_r = hkdf(length=64, derive_from=shared_r, salt=LINK_ID, context=None)
    assert key_i == key_r, "initiator/responder derived different session keys"
    return key_i


class FakeLink:
    """The minimal Link surface Resource/Packet touch, encrypting with the REAL RNS Token."""

    def __init__(self, key):
        self.token = Token(key)
        self.type = RNS.Destination.LINK
        # RNS 1.4.2 validates link liveness before resource flow-control sends.
        self.status = RNS.Link.ACTIVE
        self.hash = LINK_ID
        self.link_id = LINK_ID
        self.mtu = RNS.Reticulum.MTU
        self.mdu = RNS.Link.MDU
        self.rtt = 0.1
        self.traffic_timeout_factor = RNS.Link.TRAFFIC_TIMEOUT_FACTOR
        self.establishment_cost = 100
        self.expected_rate = None
        self.callbacks = SimpleNamespace(resource_started=None)

    def encrypt(self, plaintext):
        return self.token.encrypt(plaintext)

    def decrypt(self, ciphertext):
        return self.token.decrypt(ciphertext)

    def get_last_resource_window(self):
        return None

    def get_last_resource_eifr(self):
        return None

    def has_incoming_resource(self, resource):
        return False

    def register_incoming_resource(self, resource):
        pass

    def register_outgoing_resource(self, resource):
        pass

    def resource_concluded(self, resource):
        pass

    def ready_for_new_resource(self):
        return True


class Deterministic:
    """Patch the two entropy sources + the packet/cache side effects while Resource code runs."""

    def __init__(self):
        self.sent = []  # (context, packet_type, data) for every RNS.Packet.send

    def __enter__(self):
        self._urandom = os.urandom
        self._get_random_hash = RNS.Identity.get_random_hash
        self._send = RNS.Packet.send
        self._resend = RNS.Packet.resend
        self._cache = RNS.Transport.cache
        self._watchdog = Resource.watchdog_job

        def urandom(n):
            return IV if n == 16 else self._urandom(n)

        sent = self.sent

        def send(pkt):
            sent.append((pkt.context, pkt.packet_type, pkt.data))
            pkt.sent = True
            pkt.raw = pkt.data  # only len(raw) is consumed (receiver rate math)
            return None

        os.urandom = urandom
        RNS.Identity.get_random_hash = staticmethod(lambda: RANDOM_HASH * 4)
        RNS.Packet.send = send
        RNS.Packet.resend = send
        RNS.Transport.cache = staticmethod(lambda packet, force_cache=False: None)
        Resource.watchdog_job = lambda resource: None  # no timers/threads in vector runs
        return self

    def __exit__(self, *exc):
        os.urandom = self._urandom
        RNS.Identity.get_random_hash = self._get_random_hash
        RNS.Packet.send = self._send
        RNS.Packet.resend = self._resend
        RNS.Transport.cache = self._cache
        Resource.watchdog_job = self._watchdog
        return False


def build_sender(link, data, auto_compress):
    res = Resource(data, link, advertise=False, auto_compress=auto_compress, timeout=60)
    assert res.random_hash == RANDOM_HASH
    return res


def receive_flow(det, link, adv_bytes, parts_by_maphash, expected_data):
    """Run the REAL Python receive path on the given wire bytes; returns (requests, proof)."""
    assembled = {}

    def on_assembled(resource):
        assembled["data"] = resource.data.read()

    adv_packet = SimpleNamespace(plaintext=adv_bytes, link=link)
    rx = Resource.accept(adv_packet, callback=on_assembled)
    assert rx is not None, "RNS Resource.accept rejected the advertisement"

    requests = []
    seen = 0
    guard = 0
    while "data" not in assembled:
        guard += 1
        assert guard < 1000, "python receive flow did not converge"
        new_reqs = [d for (ctx, _pt, d) in det.sent if ctx == RNS.Packet.RESOURCE_REQ][len(requests):]
        for req in new_reqs:
            requests.append(req)
            assert req[0] == Resource.HASHMAP_IS_NOT_EXHAUSTED
            assert req[1:33] == rx.hash
            wanted = [req[33 + i * 4:37 + i * 4] for i in range((len(req) - 33) // 4)]
            for mh in wanted:
                rx.receive_part(SimpleNamespace(data=parts_by_maphash[mh], raw=parts_by_maphash[mh]))
                seen += 1
        if not new_reqs:
            time.sleep(0.01)  # assemble runs on a thread spawned by the last receive_part
    deadline = time.time() + 10
    while rx.status < Resource.COMPLETE and time.time() < deadline:
        time.sleep(0.01)
    assert rx.status == Resource.COMPLETE, f"receiver status {rx.status}"
    assert assembled["data"] == expected_data, "python reassembled different payload"
    assert seen == rx.total_parts

    proofs = [d for (ctx, pt, d) in det.sent if ctx == RNS.Packet.RESOURCE_PRF and pt == RNS.Packet.PROOF]
    assert len(proofs) == 1, "expected exactly one proof packet"
    return requests, proofs[0]


def vector(det, key, data):
    link = FakeLink(key)
    tx = build_sender(link, data, auto_compress=False)
    assert tx.compressed is False and tx.encrypted is True
    assert tx.sdu == 464

    adv_bytes = ResourceAdvertisement(tx).pack()
    parts = [p.data for p in tx.parts]
    blob = b"".join(parts)
    assert len(blob) == tx.size
    assert link.decrypt(blob)[Resource.RANDOM_HASH_SIZE:] == data

    parts_by_maphash = {p.map_hash: p.data for p in tx.parts}
    assert len(parts_by_maphash) == len(parts), "map hash collision in fixture"
    det.sent.clear()
    requests, proof = receive_flow(det, FakeLink(key), adv_bytes, parts_by_maphash, data)
    assert proof == tx.hash + tx.expected_proof, "python proof != sender expectation"

    # The sender must accept its own receiver's proof (validate_proof flips COMPLETE).
    tx.validate_proof(proof)
    assert tx.status == Resource.COMPLETE, "python sender rejected the python proof"

    return {
        "payload": data.hex(),
        "adv": adv_bytes.hex(),
        "transfer_size": tx.size,
        "data_size": tx.total_size,
        "num_parts": tx.total_parts,
        "hashmap": tx.hashmap.hex(),
        "parts": [p.hex() for p in parts],
        "resource_hash": tx.hash.hex(),
        "expected_proof": tx.expected_proof.hex(),
        "proof_packet": proof.hex(),
        "requests": [r.hex() for r in requests],
    }


def compressed_adv_vector(det, key, data):
    """A bz2-compressed ADV from real RNS — the lite receiver must parse then refuse it."""
    tx = build_sender(FakeLink(key), data, auto_compress=True)
    assert tx.compressed is True, "fixture payload did not compress"
    adv = ResourceAdvertisement(tx)
    assert adv.f & 0x02, "compressed flag not set"
    return {"payload": data.hex(), "adv": adv.pack().hex(), "transfer_size": tx.size}


def main():
    if RNS.__version__ != TARGET_RNS:
        print(f"ERROR: target RNS {TARGET_RNS}, found {RNS.__version__}", file=sys.stderr)
        return 1
    assert RNS.Link.MDU == 431 and RNS.Packet.MDU == 464
    assert ResourceAdvertisement.OVERHEAD == 134 and ResourceAdvertisement.HASHMAP_MAX_LEN == 74

    RNS.Reticulum.resourcepath = tempfile.mkdtemp(prefix="rns-lite-resource-vectors-")
    key = session_key()

    with Deterministic() as det:
        multi = vector(det, key, payload(MULTI_LEN))
        assert multi["num_parts"] == 5 and len(multi["requests"]) == 2
        single = vector(det, key, payload(SINGLE_LEN))
        assert single["num_parts"] == 1 and len(single["requests"]) == 1
        compressed = compressed_adv_vector(det, key, payload(MULTI_LEN))

    resp_x_pub = X25519PrivateKey.from_private_bytes(RESP_X).public_key().public_bytes()
    out = {
        "rns_version": RNS.__version__,
        "note": f"Resource transfer parity vectors from the REAL RNS {TARGET_RNS} Resource "
        "classes (fixed entropy, headless link). Regenerate only via gen_resource_vectors.py.",
        "init_x25519_priv": INIT_X.hex(),
        "resp_x25519_priv": RESP_X.hex(),
        "resp_x25519_pub": resp_x_pub.hex(),
        "link_id": LINK_ID.hex(),
        "session_key": key.hex(),
        "random_hash": RANDOM_HASH.hex(),
        "iv": IV.hex(),
        "multi": multi,
        "single": single,
        "compressed_adv": compressed,
    }
    here = os.path.dirname(os.path.abspath(__file__))
    with open(os.path.join(here, "resource_vectors.json"), "w") as f:
        json.dump(out, f, indent=2)
    print(f"OK: resource vectors written (RNS {RNS.__version__}).")
    print(f"  multi : t={multi['transfer_size']} n={multi['num_parts']} hash={multi['resource_hash']}")
    print(f"  single: t={single['transfer_size']} n={single['num_parts']} hash={single['resource_hash']}")
    print(f"  proof : {multi['proof_packet'][:32]}...")
    return 0


if __name__ == "__main__":
    sys.exit(main())
